services:
  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.12
    init: true
    volumes:
      - ./:/home/python/docker-pelican
    working_dir: /home/python/docker-pelican

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/pelican
    init: true
    volumes:
      - ./:/home/python/docker-pelican
    working_dir: /home/python/docker-pelican
