name: Build the container image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - published

env:
  ghcr_image_name: ghcr.io/williamjacksn/pelican
  docker_hub_image_name: williamjackson/pelican

jobs:

  build:
    name: Build the container image
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the container image
        uses: docker/build-push-action@v4.1.1
        with:
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.ghcr_image_name }}
            ${{ env.docker_hub_image_name }}

      - name: Log in to GitHub container registry
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          password: ${{ github.token }}
          username: ${{ github.actor }}

      - name: Log in to Docker Hub
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.docker_hub_password }}
          username: ${{ secrets.docker_hub_username }}

      - name: Push latest image to registries
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.ghcr_image_name }}:latest
            ${{ env.docker_hub_image_name }}:latest

      - name: Tag and push release image to registries
        if: github.event_name == 'release'
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.ghcr_image_name }}:${{ github.event.release.tag_name }}
            ${{ env.docker_hub_image_name }}:${{ github.event.release.tag_name }}
